### Variable 
@host=http://0.0.0.0:8080/api/v1
@token=v2.local.ouK-ULXPeZE0mP2l3frZbw34CdMzodpGPhVx1Gghg7cDJnNHFbwi2lU-TED7SGjIHbcXfFEkFzJvHGkeHGLSqazm_cgUgiEOBcOcHCNRz0I0TEysZLlwjNIxDaNq7q4xdgy9lCLhkVtHjA7hzXKTEi5uRL0SgyG0YMMTtG43blpsLQi_Fx5i6Ta8-qYJAmQ-mnYlLDZto1SX5JAmuQqyeRfFO9cXsQ5WI_sYuQ1tZdjJ6v1iaAFPw5iq0JLnpY0dsjkjBjjMcg.bnVsbA

###
POST {{host}}/accounts HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "currency": "IDR"
}

### 

GET {{host}}/accounts/75 HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{host}}/accounts?page_id=1&page_size=5 HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{host}}/transfers HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "from_account_id": 39,
    "to_account_id": 75,
    "amount": 100,
    "currency": "IDR"
}

###

POST {{host}}/users HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "david",
    "full_name": "john wick",
    "email": "teguh@gmail.com",
    "password": "adminadmin"
}

###

POST {{host}}/users/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "david",
    "password": "adminadmin"
}